In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Reading the Dataset
#dataset = pd.read_csv('/content/drive/MyDrive/50_Startups.csv')
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
datasets=pd.get_dummies(dataset,drop_first=True)
#repetation info sjould be drop

In [5]:
datasets

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False
5,131876.90,99814.71,362861.36,156991.12,False,True
6,134615.46,147198.87,127716.82,156122.51,False,False
7,130298.13,145530.06,323876.68,155752.60,True,False
8,120542.52,148718.95,311613.29,152211.77,False,True
9,123334.88,108679.17,304981.62,149759.96,False,False
10,101913.08,110594.11,229160.95,146121.95,True,False
11,100671.96,91790.61,249744.55,144259.40,False,False
12,93863.75,127320.38,249839.44,141585.52,True,False
13,91992.39,135495.07,252664.93,134307.35,False,False
14,119943.24,156547.42,256512.92,132602.65,True,False
15,114523.61,122616.84,261776.23,129917.04,False,True
16,78013.11,121597.55,264346.06,126992.93,False,False
17,94657.16,145077.58,282574.31,125370.37,False,True
18,91749.16,114175.79,294919.57,124266.90,True,False
19,86419.70,153514.11,0.00,122776.86,False,True
20,76253.86,113867.30,298664.47,118474.03,False,False
21,78389.47,153773.43,299737.29,111313.02,False,True
22,73994.56,122782.75,303319.26,110352.25,True,False
23,67532.53,105751.03,304768.73,108733.99,True,False
24,77044.01,99281.34,140574.81,108552.04,False,True
25,64664.71,139553.16,137962.62,107404.34,False,False
26,75328.87,144135.98,134050.07,105733.54,True,False
27,72107.60,127864.55,353183.81,105008.31,False,True
28,66051.52,182645.56,118148.20,103282.38,True,False
29,65605.48,153032.06,107138.38,101004.64,False,True
30,61994.48,115641.28,91131.24,99937.59,True,False
31,61136.38,152701.92,88218.23,97483.56,False,True
32,63408.86,129219.61,46085.25,97427.84,False,False
33,55493.95,103057.49,214634.81,96778.92,True,False
34,46426.07,157693.92,210797.67,96712.80,False,False
35,46014.02,85047.44,205517.64,96479.51,False,True
36,28663.76,127056.21,201126.82,90708.19,True,False
37,44069.95,51283.14,197029.42,89949.14,False,False
38,20229.59,65947.93,185265.10,81229.06,False,True
39,38558.51,82982.09,174999.30,81005.76,False,False
40,28754.33,118546.05,172795.67,78239.91,False,False
41,27892.92,84710.77,164470.71,77798.83,True,False
42,23640.93,96189.63,148001.11,71498.49,False,False
43,15505.73,127382.30,35534.17,69758.98,False,True
44,22177.74,154806.14,28334.72,65200.33,False,False
45,1000.23,124153.04,1903.93,64926.08,False,True
46,1315.46,115816.21,297114.46,49490.75,True,False
47,0.00,135426.92,0.00,42559.73,False,False
48,542.05,51743.15,0.00,35673.41,False,True
49,0.00,116983.80,45173.06,14681.40,False,False

In [6]:
datasets.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
indep=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dep=datasets[['Profit']]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 0.30, random_state = 0)

In [9]:
import numpy as np
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import r2_score
from sklearn.datasets import make_regression

In [10]:
# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid']
}
# Initialize SVR model
svr = SVR()

# Set up GridSearchCV
grid_search = GridSearchCV(svr, param_grid, scoring='r2', cv=5, n_jobs=-1)
#grid_search = GridSearchCV(svr, param_grid, verbose=3 (folds),n_jobs=-1)
#refit=true (best) if false its take last column, verbose=3,n_jobs=1
# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best parameters and R² score on test data
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test) #grid_prediction
r2_test = r2_score(y_test, y_pred)

print("Best Parameters:", grid_search.best_params_) #input parameters=param_grid
print("Best R² score on training set:", grid_search.best_score_)
print("R² score on test set:", r2_test)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Best Parameters: {'C': 0.1, 'kernel': 'linear'}
Best R² score on training set: 0.9236743505870948
R² score on test set: 0.9375216515526494

In [14]:
table=pd.DataFrame.from_dict(grid_search.cv_results_)
print(table)
#AttributeError: module 'pandas' has no attribute 'dataframe' its DataFrame

    mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       44.854690     47.492233         0.008688        0.001507     0.1
1        0.084300      0.029668         0.026639        0.020963     0.1
2        0.017735      0.010607         0.008369        0.002022     0.1
3        0.010714      0.002590         0.010286        0.003224     0.1
4      106.657114     49.154178         0.008220        0.004135       1
5        0.010117      0.001311         0.006940        0.003054       1
6        0.009563      0.002954         0.006520        0.001462       1
7        0.029855      0.013463         0.007770        0.001981       1
8       59.910586     40.424236         0.006285        0.002002      10
9        0.019756      0.009459         0.009190        0.002372      10
10       0.010925      0.001140         0.007866        0.001802      10
11       0.010988      0.002452         0.006754        0.003874      10
12      53.317097     18.659338         0.004045        0.002561     100
13       0.017771      0.004890         0.007692        0.001308     100
14       0.008633      0.001510         0.007720        0.000417     100
15       0.009569      0.001458         0.006987        0.001218     100

   param_kernel                           params  split0_test_score  \
0        linear   {'C': 0.1, 'kernel': 'linear'}           0.895278
1           rbf      {'C': 0.1, 'kernel': 'rbf'}          -0.034868
2          poly     {'C': 0.1, 'kernel': 'poly'}          -0.034465
3       sigmoid  {'C': 0.1, 'kernel': 'sigmoid'}          -0.034888
4        linear     {'C': 1, 'kernel': 'linear'}           0.929615
5           rbf        {'C': 1, 'kernel': 'rbf'}          -0.034640
6          poly       {'C': 1, 'kernel': 'poly'}          -0.030621
7       sigmoid    {'C': 1, 'kernel': 'sigmoid'}          -0.034844
8        linear    {'C': 10, 'kernel': 'linear'}          -0.765126
9           rbf       {'C': 10, 'kernel': 'rbf'}          -0.032364
10         poly      {'C': 10, 'kernel': 'poly'}           0.002786
11      sigmoid   {'C': 10, 'kernel': 'sigmoid'}          -0.034400
12       linear   {'C': 100, 'kernel': 'linear'}        -256.190980
13          rbf      {'C': 100, 'kernel': 'rbf'}          -0.012162
14         poly     {'C': 100, 'kernel': 'poly'}           0.223139
15      sigmoid  {'C': 100, 'kernel': 'sigmoid'}          -0.029973

    split1_test_score  split2_test_score  split3_test_score  \
0            0.945175           0.929322           0.875981
1           -0.002435          -0.022112          -0.000287
2           -0.001984          -0.021455          -0.000362
3           -0.002465          -0.022130          -0.000281
4            0.937566           0.934012           0.620542
5           -0.002159          -0.021954          -0.000383
6            0.002341          -0.015396          -0.001148
7           -0.002456          -0.022129          -0.000326
8           -5.258987           0.639465          -5.375574
9            0.000598          -0.020375          -0.001352
10           0.040636           0.036478          -0.010021
11          -0.002373          -0.022127          -0.000777
12        -497.427099        -278.753049        -629.646923
13           0.023455          -0.007164          -0.011548
14           0.339001           0.385727          -0.171422
15          -0.001547          -0.022101          -0.005320

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0            0.972616         0.923674        0.034556                1
1           -0.000268        -0.011994        0.014082               12
2            0.000452        -0.011563        0.014028                8
3           -0.000282        -0.012009        0.014086               14
4            0.944071         0.873161        0.126398                2
5           -0.000140        -0.011855        0.014029               10
6            0.007038        -0.007557        0.013751                6
7           -0.000279        -0.012007        0.014065               13
8            0.312799        -2.089485        2.676423               15
9            0.001140        -0.010470        0.013549                7
10           0.070720         0.028120        0.028767                4
11          -0.000252        -0.011986        0.013863               11
12         -28.495876      -338.102785      208.072389               16
13           0.013695         0.001255        0.014577                5
14           0.414987         0.238286        0.215033                3
15           0.000012        -0.011786        0.012025                9

In [18]:
#save the best model
import pickle
filename="final_model_svm_grid.sav"
#pickle.dump(regressor,open(filename,'wb'))
#NameError: name 'regressor' is not defined  regressor=grid_search.fit(X_train, y_train)
pickle.dump(grid_search.fit(X_train, y_train),open(filename,'wb'))

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
#load  the model
loaded_model=pickle.load(open("final_model_svm_grid.sav",'rb'))

In [20]:
#result fixed inputpass
res=loaded_model.predict([[2000,1000,3000,1,1]])
#future prediction
print("res={}".format(res))

res=[43768.38471418]

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [ ]:
##---end------

In [ ]:
#re=grid_search.cv_results_    ## Set up GridSearchCV  should same grid_search or grid.
#table=pd.DataFrame.from_dict(re)
#print(table)

In [ ]:
#old
import numpy as np
# Import SVR instead of SVC
from sklearn.svm import SVR
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report

In [15]:
# old

# Define hyperparameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    #'gamma': ['scale', 'auto'],  # 'gamma' is important for rbf, poly, and sigmoid kernels
}

# Use SVR (regression) instead of SVC(classification)
grid_search = GridSearchCV(SVR(), param_grid, cv=5, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Output the best parameters and corresponding score
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validation Accuracy:", grid_search.best_score_)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Best Parameters: {'C': 0.1, 'kernel': 'linear'}
Best Cross-Validation Accuracy: -110736495.14140126

In [ ]:
#model creation
#from sklearn.svm import SVR
#regressor=SVR(kernel="linear",C=0.1)
#regressor=regressor.fit(X_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
# GridSearchCV to find the best parameters
#https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html
#default regression:class sklearn.svm.SVR(*, kernel='rbf', degree=3, gamma='scale', coef0=0.0, tol=0.001, C=1.0, 
#epsilon=0.1, shrinking=True, cache_size=200, verbose=False, max_iter=-1)[source]
#classification----svc
#SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, 
#class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)